networks:
  mynetwork:
    external: true

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/data
    network_mode: host
    extra_hosts:
      #- "cachedb120k:10.10.8.120"
      - "host.docker.internal:host-gateway"
    # ports:
    #   - "9090:9090"

volumes:
  prometheus-data: