global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "mongo-repl"
    metrics_path: /metrics
    scheme: http
    static_configs:
      # Replace me
      - targets: ["localhost:3000"]