# Define the logging policy
# level are panic, fatal, error, warn, info, debug
# If you want, you can override this configuration using the environment variable LOG_LEVEL
logging:
  level: info

# Define the replication
repl:
  
  # Define the replication id
  # This is used to store the replication state
  # The default value is "default"
  id: "rs0_to_rs1_sample"

  # Mongo source et target configuration
  # Eventually, you can override those using environment variables
  # SOURCE and TARGET
  source: mongodb://localhost:27017/db?replicaSet=rs0&retryWrites=true&w=majority
  target: mongodb://localhost:37017/db?replicaSet=rs1&retryWrites=true&w=majority

  # Define the database to replicate
  databases:
    - Animals
    - Plants

  # Filter the collections to include or exclude.
  # If both are defined, the filter_in will have the priority.
  filters:
    in:
    out:

  # Full replication configuration
  full:
  
    # Batch size for replication
    batch: 1000

    # Option to try an update in case of duplicate key
    update_on_duplicate: false

  # Incremental replication configuration
  incr:
    # Define where to store the replication state for the oplog
    state:
      db: MongoRepl
      collection: _repl
