name: Build Main and Enable Tagging

on:
  pull_request:
    types: [closed]  # Trigger only on PR close events
  workflow_run:
    workflows: [Build Feature Branch]
    types:
      - completed

jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Set your Go version here

      - name: Build project
        run: go build ./...

      - name: Run tests
        run: go test ./...

  tag-repo:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate tag
        id: generate-tag
        run: |
          TAG_NAME="v$(date +%Y%m%d).${{ github.run_number }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Output created tag
        run: echo "Tag $TAG_NAME has been created."
