name: build-main

on:
  pull_request:
    types: [closed]  # Trigger only on PR close events
  workflow_run:
    workflows: [build-branch]
    types:
      - completed

jobs:
  build-main:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/build-go-project.yml
    with:
      main-src: "./cmd/repl/main.go"

  tag-repo:
    needs: build
    if: success() && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/tag-repo.yml
    with:
      tag-name: ${{ needs.build.outputs.tag-name }}
