name: build-main
on:
  # Run this workflow only for commits to the main branch or when a PR is merged to the main branch
  push:
    branches:
      - "*" # Run this workflow for all branches
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-main:
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      main-src: "./cmd/repl/main.go"