name: build-main
on:
  # Run this workflow only for commits to the main branch
  # Will be removed !!
  push:
    branches:
      - main 

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-main:
    uses: ./.github/workflows/reusable-go-build.yml
    with:
      main-src: "./cmd/repl/main.go"