name: build-main

on:
  pull_request:
    types: [closed]  # Trigger only on PR close events
  workflow_run:
    workflows: [build-branch]
    types:
      - completed

jobs:
  build-main:
    # Run this job only for commits to the main branch or when a PR is merged to the main branch
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.base.ref == 'main' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build-go-project.yml
    with:
      main-src: "./cmd/repl/main.go"

  tag-repo:    
    needs: build-main
    uses: ./.github/workflows/tag-repo.yml
    with:
      tag-name: ${{ needs.build.outputs.tag-name }}
