name: Build Feature Branch

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22  # Set your Go version here
      
      - name: Install dependencies
        run: go mod download
      
      - name: Build project
        run: go build ./cmd/repl/main.go

      - name: Run tests
        run: go test ./...
