name: publish
on:
  push:
    tags:
      - '*'

jobs:
  
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: setup-docker
        uses: docker/setup-buildx-action@v1

      - name: log-to-docker-hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build-and-push-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mongo-repl:${{ github.ref_name }}