# This is a reusable workflow that builds a Go project.
name: reusable-tag-repo
on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version to tag the repository with'
        required: true
        default: 'v0.0.0'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: validate-tag
        id: validate-tag
        run: |
          TAG_NAME="${{ github.event.inputs.version }}"
          if [[ ! $TAG_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag name: $TAG_NAME"
            exit 1
          fi
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      
      - name: generate-tag
        id: generate-tag
        # Generate tag name from workflow incremental run number if not provided
        run: |
          TAG_NAME="${{ github.event.inputs.version }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        
      - name: tag-repo
        env:
          # Use a dedicated PAT token to be able to retrigger a workflow
          # See : https://github.com/orgs/community/discussions/27028
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
