# This is a reusable workflow that builds a Go project.
name: tag-repo
on:
  workflow_dispatch:
    inputs:
      tag-name:
        description: 'The name of the tag to create'
        required: true
        type: string
  workflow_call:
    inputs:
      tag-name:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate tag
        id: generate-tag
        run: |
          TAG_NAME="${{ inputs.tag-name }}"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "***@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
