# This is a reusable workflow that builds a Go project.
name: tag-repo
on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: generate-tag
        id: generate-tag
        # Generate tag name from workflow incremental run number
        run: |
          TAG_NAME="$GITHUB_RUN_NUMBER"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: tag-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG_NAME
          git push origin $TAG_NAME
